-- Documents table
CREATE TABLE [dbo].[DOCUMENTS] (
    [DOCUMENT#] INT NOT NULL PRIMARY KEY,
    [TYPE] NVARCHAR(50) NOT NULL
);

-- User table creation with constraints
CREATE TABLE [dbo].[USER] (
    [ID] INT NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(100) NOT NULL,
    [Birthdate] SMALLDATETIME NOT NULL,
    [Address] NVARCHAR(255) NOT NULL,
    [Phone_Number] NVARCHAR(15) NOT NULL,
    [Role_Type] NVARCHAR(50) NOT NULL CHECK ([Role_Type] IN ('Physical', 'Company')), -- User role constraint
    [Username] NVARCHAR(50) NOT NULL UNIQUE,
    [Password] NVARCHAR(50) NOT NULL,
    [Email] NVARCHAR(100) NOT NULL,
    [DOCUMENT#] INT NULL FOREIGN KEY REFERENCES [DOCUMENTS]([DOCUMENT#]) ON UPDATE CASCADE -- On cascade update of documents
);

-- Subsity Categories table with allowed categories
CREATE TABLE [dbo].[SUBSITY_CATEGORIES] (
    [CATEGORY_NUMBER] NVARCHAR(10) NOT NULL PRIMARY KEY CHECK ([CATEGORY_NUMBER] IN ('Γ1', 'Γ2', 'Γ3', 'Γ4', 'Γ5', 'Γ6', 'Γ7', 'Γ8', 'Γ10', 'Γ11', 'Γ12', 'Γ13', 'Γ14')),
    [AMOUNT] DECIMAL(10, 2) NOT NULL,
    [AVAILABLE_SUBSITY_NUMBER] INT NOT NULL
);

-- Criteria for Validation table
CREATE TABLE [dbo].[CRITERIA_FOR_VALIDATION] (
    [CRITERIA#] INT NOT NULL PRIMARY KEY,
    [DESCRIPTION] NVARCHAR(255) NOT NULL,
    [CATEGORY_NUMBER] NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES [dbo].[SUBSITY_CATEGORIES]([CATEGORY_NUMBER])
);

-- Application table with enhancements
CREATE TABLE [dbo].[APPLICATION] (
    [APPLICATION#] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [DATE] SMALLDATETIME NOT NULL,
    [ID] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[USER]([ID]) ON DELETE CASCADE, -- On delete of user, delete all their applications
    [CATEGORY_NUMBER] NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES [dbo].[SUBSITY_CATEGORIES]([CATEGORY_NUMBER]),
    [Status] NVARCHAR(50) NOT NULL DEFAULT 'Pending Review', -- Default status is 'Pending Review'
    CHECK ([CATEGORY_NUMBER] IN ('Γ1', 'Γ2', 'Γ3', 'Γ4', 'Γ5', 'Γ6', 'Γ7', 'Γ8', 'Γ10', 'Γ11', 'Γ12', 'Γ13', 'Γ14'))
);

-- Vehicle Order table
CREATE TABLE [dbo].[VEHICLE_ORDER] (
    [ORDER#] INT NOT NULL PRIMARY KEY,
    [ORDER_DATE] SMALLDATETIME NOT NULL,
    [APPLICATION#] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[APPLICATION]([APPLICATION#])
);

-- Vehicles table
CREATE TABLE [dbo].[VEHICLES] (
    [REGISTRATION#] NVARCHAR(15) NOT NULL PRIMARY KEY,
    [TYPE] NVARCHAR(50) NOT NULL,
    [CONDITION] NVARCHAR(50) NOT NULL,
    [MANUFACTURE_DATE] SMALLDATETIME NOT NULL,
    [CATEGORY] NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES [dbo].[SUBSITY_CATEGORIES]([CATEGORY_NUMBER]),
    [ORDER#] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[VEHICLE_ORDER]([ORDER#])
);

-- Change table
CREATE TABLE [dbo].[CHANGE] (
    [CHANGE#] INT NOT NULL PRIMARY KEY,
    [HISTORY] NVARCHAR(255) NOT NULL,
    [DATE] SMALLDATETIME NOT NULL,
    [REASON] NVARCHAR(255) NOT NULL,
    [Status] NVARCHAR(50) NOT NULL,
    [APPLICATION#] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[APPLICATION]([APPLICATION#])
);